# .scrutinizer.yml

filter:
    paths: [ src/* ]

before_commands:
    - "composer install --prefer-source"

tools:
    #external_code_coverage: true
    php_cpd: true
    php_pdepend: true
    php_code_coverage: true
    php_analyzer: true

changetracking:
    bug_patterns: ["\bfix(?:es|ed)?\b"]
    feature_patterns: ["\badd(?:s|ed)?\b", "\bimplement(?:s|ed)?\b"]

checks:
    php:
        excluded_dependencies:
            - zendframework/zend-loader
            - zendframework/zend-escaper
            - zendframework/zend-http
            - zendframework/zend-loader
            - zendframework/zend-math
            - zendframework/zend-stdlib
            - zendframework/zend-validator
            - zendframework/zend-xmlrpc
            - zendframework/zend-code
            - zendframework/zend-eventmanager
            - zendframework/zend-json
            - zendframework/zend-server
            - zendframework/zend-soap
            - zendframework/zend-uri
